### ISSUE TITLE
Upgrade to latest Selenium.Axe and Selenium.WebDriver packages (OSOE-49)

### ISSUE THREAD

**Issue by Piedone** [Lombiq/UI-Testing-Toolbox#123]
We're one major version behind, the current version is Selenium 4. We need to update Atata to get these.

- New features and differences: https://www.browserstack.com/guide/selenium-4-features
- For Atata v2 changes see: https://github.com/atata-framework/atata/releases/tag/v2.0.0 Migration guide: https://atata.io/tutorials/migrating-to-atata-v2/
- Add `Driver.ExecuteScript()` and `Driver.GetScreenshot()` shortcuts.
- Perhaps the newer Selenium.Axe version fixes that it accepts the `title` of an `img` instead of (also) insisting on `alt`.
- Search the codebase for "Selenium 4" and apply fixes appropriately.
- Also update all other packages that the Toolbox uses.

**Comment by sarahelsaig** [comment]
Do we really need `Driver.ExecuteScript()` and `Driver.GetScreenshot()` shortcuts?
We already have `UITestContext.ExecuteScript`, `UITestContext.ExecuteAsyncScript` and `UITestContext.TakeScreenshot`.

**Comment by Piedone** [comment]
Indeed, then we don't.
