### ISSUE TITLE
Offer security checks (OSOE-351)

### ISSUE THREAD

**Issue by Piedone** [Lombiq/UI-Testing-Toolbox#128]
Perhaps integrate with some tool that can test a form for XSS vulnerability or something like that. Need to look around. 

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-351)

**Comment by Piedone** [comment]
We could explore using [ZAP](https://www.zaproxy.org/).

- They also offer GitHub Actions: https://github.com/marketplace?query=zap&verification=verified_creator
  - These simply run the [packaged scans](https://www.zaproxy.org/docs/docker/about/#packaged-scans) though, see [eg. here](https://github.com/zaproxy/action-full-scan/blob/master/index.js#L53).
  - For an OC app, we'd need the API and Full Scans.
  - If we use these actions, then the app needs to be kept running even after test execution finishes, which seems problematic. Rather, we'd need to run the Docker commands from within the tests, after switching the app to interactive mode. Then, at the end of the scan, we can switch back from interactive mode (either by instructing ZAP to open `InteractiveModeController.Continue` or by setting `IInteractiveModeStatusAccessor.Enabled` directly).
- Instead of packaged scans, ZAP is migrating to the new [Automation Framework](https://www.zaproxy.org/docs/docker/about/#automation-framework). `zap-weekly` uses the Automation Framework as the baseline scan already, we should use that. We can create such an Automation Framework YAML in the desktop app and then use it to run a scan by default.
- Using ZAP to proxy UITT browser interactions would perhaps be the best, in addition to starting scans in a browser opened by UITT. If the latter is not possible, then we can configure the login shortcut to handle [authentication](https://www.zaproxy.org/docs/desktop/start/features/authentication/) (also see [users](https://www.zaproxy.org/docs/desktop/start/features/users/)).
  - For this, we need to configure Docker to allow access to the app running on localhost in the host, which the mentioned actions do.
  - Others [have thought about this](https://groups.google.com/g/zaproxy-users/c/0rzwX1b3_5w?pli=1) too.
  - There's a [.NET API package](https://github.com/zaproxy/zap-api-dotnet) but that [only supports .NET Framework](https://github.com/zaproxy/zap-api-dotnet/issues/16).
- Similar to accessibility checks, there should be a way to run these scans for every page view (with ZAP's proxy feature) or explicitly, either for only the current page or like monkey tests, unleashing a scan with the spider. Also similar to accessibility checks, there should be a way to always create a report (see `AccessibilityCheckingConfiguration.CreateReportAlways`).
-  To be able to assert on the report from a test, we need a machine-readable version of it. [ZAP's SARIF report](https://github.com/zaproxy/zaproxy/issues/6875) seems suitable for this ([sample report](https://www.zaproxy.org/docs/desktop/addons/report-generation/report-sarif-json/)).  This is available with the `report_json` switch for packaged scans. We need to save this and also the human-readable pretty report to the Failure Dump. The `report_html` or `report_md` switches can do this (perhaps also add the report to the workflow summary?).
- ZAP's full configuration should be surfaced in its native way, most possibly with the YAML approach of [Automation Framework](https://www.zaproxy.org/docs/docker/about/#automation-framework).
- Check if there are ZAP plugins that are useful for us, like [Attack Surface Detector](https://github.com/secdec/attack-surface-detector-zap/wiki). These need to be possible to easily run locally in GHA.
- We need a separate ZAP instance for each scan.
- We could integrate with GitHub Code Scanning, see https://github.com/zaproxy/action-baseline/issues/63 and https://github.com/SvanBoxel/zaproxy-to-ghas. Docs on integration is [here](https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/about-integration-with-code-scanning). This needs SARIF export, see [here](https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/sarif-support-for-code-scanning). However, this doesn't seem necessary, since we'd fail the build on any security issue anyway.

**Comment by Piedone** [comment]
There's also a long list of suitable tools by OWASP here: https://owasp.org/www-community/Source_Code_Analysis_Tools. I checked these out, only the open-source tools supporting .NET (since this list about code scanning, unlike ZAP). Didn't find anything better than what we already use in .NET Analyzers.

**Comment by BenedekFarkas** [comment]
We should also investigate using https://codeql.github.com/, AFAIK it partially overlaps with https://github.com/Lombiq/.NET-Analyzers too.

**Comment by Piedone** [comment]
That looks like something [we'd configure for code scanning](https://docs.github.com/en/code-security/code-scanning/introduction-to-code-scanning/about-code-scanning-with-codeql) or run in a CI workflow with [the CodeQL Action](https://github.com/github/codeql-action/). And yeah, this is rather static code analysis than something related to UI testing.

We can look into trying it out on OSOCE (since unless you use Enterprise, it's only available for public repos) with LGHA. Will you open an issue in the latter or shall I?

**Comment by BenedekFarkas** [comment]
Yes, here are my initial findings too: https://github.com/Lombiq/GitHub-Actions/issues/283

Also found this: https://github.com/apisec-inc/ethicalcheck-action, worth comparing with ZAP.

**Comment by Piedone** [comment]
That looks the same as ZAP's OpenAPI scan.
