### ISSUE TITLE
Use a version of CultureScope that doesn't have user overrides (OSOE-350)

### ISSUE THREAD

**Issue by sarahelsaig** [Lombiq/UI-Testing-Toolbox#133]
This is related to https://github.com/OrchardCMS/OrchardCore/issues/11228
The _useUserOverride_ in `CultureInfo(string Culture, bool useUserOverride)` should be always false in UI tests to make them more reproducible and portable. Depending on how the above linked issue goes, we should either force default configuration or replace it with a custom implementation that uses the method suggested in the issue description.

After this, [this line in Data Tables](https://github.com/Lombiq/Orchard-Data-Tables/blob/c969627f4d916ece5b77eabbd9acc52661af08c4/Lombiq.DataTables.Samples/Views/Sample/DataTableTagHelper.cshtml#L16) needs to be changed too.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-350)

**Comment by Piedone** [comment]
Once https://github.com/OrchardCMS/OrchardCore/pull/12467 is merge, I think we can just update the _appsettings.json_s (the root ones) for our sites, and update the docs here to recommend that.
