### ISSUE TITLE
Custom logging instead of NLog-based one (OSOE-402)

### ISSUE THREAD

**Issue by Piedone** [Lombiq/UI-Testing-Toolbox#206]
Currently, the UI Testing Toolbox depends on NLog. In `OrchardApplicationFactory` we configure NLog for logging, and `OrchardCoreInstance.GetLogs()` we load the log files. Instead, while retaining support for the app under test to use NLog logging for its own reasons, we could have our custom in-memory logger just for testing. That'd collect log messages about errors and warnings, and we'd use that to check for log entries to fail the test.

Decoupling the project from NLog would also prevent issues like this when Orchard updates its NLog version: https://github.com/OrchardCMS/OrchardCore/pull/11194#issuecomment-1281160575

Related: https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/pull/264#discussion_r1016836343

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-402)

**Comment by rikbosch** [comment]
Could something like https://github.com/horsdal/InMemoryLogger/blob/master/src/InMemoryLogger.cs be a solution?

**Comment by Piedone** [comment]
Yep, looks suitable. Through `InMemoryLogger.RecordedLogs` we could also access the log entries.

In any case, the FailureDump should still contain a full log file.

**Comment by rikbosch** [comment]
What about using OpenTelemetry for capturing logs / traces and metrics of a specific failed test?

**Comment by Piedone** [comment]
That could be useful for tracing tests in general, though well beyond the scope of this issue, which is about substituting the `ILogger` implementation.

See also https://github.com/OrchardCMS/OrchardCore/issues/12251.

**Comment by Piedone** [comment]
Perhaps the best would be to use [`FakeLogger`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.testing.fakelogger-1). Then [`FakeLogCollector`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.testing.fakelogcollector) can be used to retrieve the log messages.

**Comment by Piedone** [comment]
This would also allow us to better filter log messages. Thus, we wouldn't log `ErrorController`'s exception, to begin with, instead of filtering it out during assertion.

**Comment by Piedone** [comment]
It's important that we need to log URLs too, since this greatly improved troubleshooting from a failure dump.

**Comment by Piedone** [comment]
For the record:

`FakeLogger` is really simple, and it can only provide very rudimentary filtering based on log levels (or the type that logs, but that's only an allow list, i.e. we can only configure it to log for specific classes). The log level can't be set per type, nor can there be any custom filtering. But it works.

[`InMemoryLogger`](https://github.com/horsdal/InMemoryLogger) is unmaintained and also very rudimentary.

[`Logging.Memory`](https://github.com/iflight/Logging.Memory) has [custom filtering](https://github.com/iflight/Logging.Memory/blob/master/Logging.Memory/src/Logging.Memory/MemoryLogger.cs#L34) (though this seems only for category and level), but is unmaintained, with 3 PRs being open that address issues all important for this use case.

Finally, [`Meziantou.Extensions.Logging.InMemory](https://github.com/meziantou/Meziantou.Framework/tree/main/src/Meziantou.Extensions.Logging.InMemory) is also very rudimentary.
