### ISSUE TITLE
IsUITesting() always returns false (OSOE-412)

### ISSUE THREAD

**Issue by Piedone** [Lombiq/UI-Testing-Toolbox#217]
As reported by @DemeSzabolcs.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-412)

**Comment by Piedone** [comment]
Do you really need to update the NuGet reference in all projects? I don’t think all the submodules are necessary. Consolidation doesn't affect the dependencies only used during NuGet publishing.

**Comment by Piedone** [comment]
It seems to me that only publishing Application Insights should be enough (due to its own changes, not for this issue), and otherwise, only publishing Lombiq.Tests.UI* projects, and updating the NuGet references in the test projects, are necessary.

**Comment by dministro** [comment]
I'm not sure, updating only `Lombiq.Tests.UI*` NuGet references are enough. If you have resource changes between the NuGet version (e.g. recipes) using different versions for `Lombiq.Tests.UI*` and the module itself can cause mystic errors, and looks ugly :)

**Comment by dministro** [comment]
> Do you really need to update the NuGet reference in all projects? I don’t think all the submodules are necessary. Consolidation doesn't affect the dependencies only used during NuGet publishing.

If I remember well, updating UITT reference only in one module (in this case Application Insight) is not enough, the consolidating reports error in NuGet test.

**Comment by Piedone** [comment]
What I'm saying is, that you have to only update UITT in the following places for its changes to take effect:

- The UI test project in the NuGetTest solution (also necessary in the root solution but that's given due to using the source).
- The web project in the NuGetTest solution.
- If a module-specific UI test project, like that of AI, uses new APIs from UITT, then that as well, but only then.

This way, even if module-specific UI test projects may reference an older version of UITT, the whole thing should properly work, since at the root of the dependency chain, the app that actually runs and ultimately loads the packages, the latest UITT is used.

**Comment by dministro** [comment]
In general, you are right, but if I do a version update the way you write, and update UITT version only one NuGet (in this case AI), the NuGet test is fail in `verify-dotnet-consolidation`. I'm not tried nowadays, but a few weeks ago the consolidation check failed, in a similar case.

**Comment by Piedone** [comment]
I thought that won't happen, since donsolidation refers to projects (not NuGet packages) referencing the same version of a given project. While our projects do that with UITT, only in `NuGetBuild`, so the source build shouldn't be affected. But you're right, `dotnet-consolidate` just looks at the references and doesn't care about the conditions in the csprojs, so these updates are necessary: https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/3322274303/jobs/5491064235#step:4:46

**Comment by dministro** [comment]
Sorry, I remembered only the result and the reason for the situation.
