### ISSUE TITLE
Invalid character in artifact path (OSOE-601)

### ISSUE THREAD

**Issue by DemeSzabolcs** [Lombiq/UI-Testing-Toolbox#267]
When a test fails, it seems like the browser type is included in the artifact path:

`Error: Artifact path is not valid: /test/Project.Tests.UI/bin/Debug/net6.0/artifacts/20230327T100017/Project.Tests.UI.Tests.ProjectTests.VisualVerificationTests.VisualVerificationTests.VerifyProjectPage(browser: Chrome)/01 - FailureDumpPageSnapshot.mhtml. Contains the following character:  Colon :`

That causes an error because it includes a colon.

This most likely only happens with visual verification tests.

Here is a sample in OSOCE for this problem: https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/4534487655/jobs/7988726362?pr=438#step:9:12434

Log archive if the logs are deleted:
[logs_8706.zip](https://github.com/Lombiq/UI-Testing-Toolbox/files/11081315/logs_8706.zip)

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-601)

**Comment by Piedone** [comment]
Where is that error happening, excactly?

**Comment by DemeSzabolcs** [comment]
> Where is that error happening, excactly?

In the `Tests` step, after testing and while running `actions/upload-artifact@v3.1.1`. So I think the problem is in Lombiq.UITestingToolbox.

**Comment by Piedone** [comment]
Please provide a log sample.

**Comment by Piedone** [comment]
Here it is one: https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/4534487655/jobs/7988726362?pr=438#step:9:12434

**Comment by DemeSzabolcs** [comment]
I already added that to the description.

**Comment by Piedone** [comment]
OK, great (there are no notifications about such edits so I didn't know).

**Comment by DemeSzabolcs** [comment]
Context on what is happening:

Atata creates the artifact folder. Inside it, it creates {date-time}/{test-name-with-browser}. And it's like this `browser: Chrome`. On Windows it's just `browser Chrome`, but Ubuntu allows `:` in folder names. So on the CI, it will be `browser: Chrome`. 

If Blame Hang Timeout is turned on, it also uploads an artifact. But this artifact contains the mentioned folder with `:` in the name. And GH `actions/upload-artifact` throws an error because of this (which is valid). So we just have to rename those folders (remove `:`) when copying them.

**Comment by dministro** [comment]
Fixed by https://github.com/Lombiq/GitHub-Actions/pull/224
