### ISSUE TITLE
Add interactive mode for debugging (OSOE-634)

### ISSUE THREAD

**Issue by sarahelsaig** [Lombiq/UI-Testing-Toolbox#281]
An updated copy of my original post [on Teams](https://teams.microsoft.com/l/message/19:0e3ad2d722c74eef93386ecfeb790963@thread.skype/1684684989599?tenantId=959ede5a-38e9-44e6-adc8-85553beb8220&groupId=00c48e7c-aebf-4247-84cf-bb7c31061ef1&parentMessageId=1684684989599&teamName=Open%20Source%20Orchard%20Extensions%20developers&channelName=General&createdTime=1684684989599&allowXTenantAccess=false):

Back when the UI tests started the web app in a separate process, it was possible to just drop a breakpoint in your code and do stuff in the browser window interactively, because the program was still running. So you could still look around on other pages, inspect the current state of the admin dashboard, etc. It was only needed occasionally but then it was incredibly useful in debugging problems that crop up during UI tests. 

Right now this is not possible. Currently the only hack where I can approximate this effect is by adding something like await `Task.Delay(120000);` before the line where I'd like to "break", and then I have 2 minutes to look around in another tab but that's super inconvenient. 

I'd like to have the ability to switch into an interactive mode programmatically, similar to how you can switch into debug mode with `Debugger.Break()`. I envision a separate module that stores a mode state and exposes an MVC action for a UI to leave interactive mode and continue operation. This module would be added to the webapp just like the Shortcuts module now. And an `await context.SwitchToInteractiveAsync()` extension method that updates the mode, opens this action in a new tab and then waits until the state is restored, e.g. via task cancellation.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-634)

**Comment by Piedone** [comment]
We don't really need a separate module for this, it can be part of Shortcuts.

Having a new tab open with a button like "Exit interactive mode" would be beautiful, though I think even having a URL that you open that quits interactive mode would be sufficient.

**Comment by sarahelsaig** [comment]
I'm doing both. Visually it will open the tab like
![image](https://github.com/Lombiq/UI-Testing-Toolbox/assets/4007293/9f8a2a96-db2d-42fb-9dcc-4ade64c71a2c)
but you can also directly navigate to `~/Lombiq.Tests.UI.Shortcuts/InteractiveMode/Continue` to get the same effect.

**Comment by Piedone** [comment]
Looks awesome!
