### ISSUE TITLE
Remove references to Internet Explorer (OSOE-663)

### ISSUE THREAD

**Issue by sarahelsaig** [Lombiq/UI-Testing-Toolbox#299]
Internet Explorer has been dead for little over a year. Do we use `[InternetExplorer]` anywhere?
If not, I suggest removing related code & documentation, and marking the attribute obsolete. We wouldn't want any support obligations for a discontinued browser.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-663)

**Comment by Piedone** [comment]
Yep!
