### ISSUE TITLE
Fix the BasicVisualVerificationTests.VerifyNavbar sample (OSOE-755)

### ISSUE THREAD

**Issue by Piedone** [Lombiq/UI-Testing-Toolbox#329]
Because it started to fail [like this](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/7158480532) under Windows.

> [VisualVerificationBaselineImageNotFoundException in Lombiq.Tests.UI.Samples.Tests.BasicVisualVerificationTests.VerifyNavbar(browser: Chrome): test/Lombiq.UITestingToolbox/Lombiq.Tests.UI.Samples/Tests/BasicVisualVerificationTests.cs#L72](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/commit/93a6fda570b3ea6aa0c67cc983177e26be19f09d#annotation_16301364131)
Lombiq.Tests.UI.Exceptions.VisualVerificationBaselineImageNotFoundException: Baseline image file was not found under the path D:\a\Open-Source-Orchard-Core-Extensions\Open-Source-Orchard-Core-Extensions\test\Lombiq.UITestingToolbox\Lombiq.Tests.UI.Samples\Tests\BasicVisualVerificationTests_VerifyNavbar_By_ClassName[Contains]_-navbar-brand_Win32NT_chrome-headless-shell.png and maxRetryCount is set to 2, so it won't be generated.    at Lombiq.Tests.UI.Extensions.VisualVerificationUITestContextExtensions.AssertVisualVerificationApproved(UITestContext context, IWebElement element, Action`2 comparator, Nullable`1 regionOfInterest, Action`1 configurator) in D:\a\Open-Source-Orchard-Core-Extensions\Open-Source-Orchard-Core-Extensions\test\Lombiq.UITestingToolbox\Lombiq.Tests.UI\Extensions\VisualVerificationUITestContextExtensions.cs:line 400    at Lombiq.Tests.UI.Extensions.VisualVerificationUITestContextExtensions.AssertVisualVerificationApproved(UITestContext context, By elementSelector, Action`2 comparator, Nullable`1 regionOfInterest, Action`1 configurator) in D:\a\Open-Source-Orchard-Core-Extensions\Open-Source-Orchard-Core-Extensions\test\Lombiq.UITestingToolbox\Lombiq.Tests.UI\Extensions\VisualVerificationUITestContextExtensions.cs:line 309    at Lombiq.Tests.UI.Extensions.VisualVerificationUITestContextExtensions.AssertVisualVerificationApproved(UITestContext context, By elementSelector, Double pixelErrorPercentageThreshold, Nullable`1 regionOfInterest, Action`1 configurator) in D:\a\Open-Source-Orchard-Core-Extensions\Open-Source-Orchard-Core-Extensions\test\Lombiq.UITestingToolbox\Lombiq.Tests.UI\Extensions\VisualVerificationUITestContextExtensions.cs:line 141    at Lombiq.Tests.UI.Samples.Tests.BasicVisualVerificationTests.<>c.<VerifyNavbar>b__2_0(UITestContext context) in D:\a\Open-Source-Orchard-Core-Extensions\Open-Source-Orchard-Core-Extensions\test\Lombiq.UITestingToolbox\Lombiq.Tests.UI.Samples\Tests\BasicVisualVerificationTests.cs:line 72    at Lombiq.Tests.UI.Extensions.AsyncExtensions.<>c__DisplayClass0_0`1.<AsCompletedTask>b__0(T target) in D:\a\Open-Source-Orchard-Core-Extensions\Open-Source-Orchard-Core-Extensions\test\Lombiq.UITestingToolbox\Lombiq.Tests.UI\Extensions\AsyncExtensions.cs:line 11    at Lombiq.Tests.UI.Services.UITestExecutionSession`1.ExecuteAsync(Int32 retryCount, String dumpRootPath) in D:\a\Open-Source-Orchard-Core-Extensions\Open-Source-Orchard-Core-Extensions\test\Lombiq.UITestingToolbox\Lombiq.Tests.UI\Services\UITestExecutionSession.cs:line 114    at Lombiq.Tests.UI.Services.UITestExecutionSession`1.ExecuteAsync(Int32 retryCount, String dumpRootPath) in D:\a\Open-Source-Orchard-Core-Extensions\Open-Source-Orchard-Core-Extensions\test\Lombiq.UITestingToolbox\Lombiq.Tests.UI\Services\UITestExecutionSession.cs:line 138    at Lombiq.Tests.UI.Services.UITestExecutionSession`1.ExecuteAsync(Int32 retryCount, String dumpRootPath) in D:\a\Open-Source-Orchard-Core-Extensions\Open-Source-Orchard-Core-Extensions\test\Lombiq.UITestingToolbox\Lombiq.Tests.UI\Services\UITestExecutionSession.cs:line 151    at Lombiq.Tests.UI.Services.UITestExecutor.ExecuteOrchardCoreTestInnerAsync[TEntryPoint](UITestManifest testManifest, OrchardCoreUITestExecutorConfiguration configuration, String dumpRootPath) in D:\a\Open-Source-Orchard-Core-Extensions\Open-Source-Orchard-Core-Extensions\test\Lombiq.UITestingToolbox\Lombiq.Tests.UI\Services\UITestExecutor.cs:line 83    at Lombiq.Tests.UI.Services.UITestExecutor.ExecuteOrchardCoreTestInnerAsync[TEntryPoint](UITestManifest testManifest, OrchardCoreUITestExecutorConfiguration configuration, String dumpRootPath) in D:\a\Open-Source-Orchard-Core-Extensions\Open-Source-Orchard-Core-Extensions\test\Lombiq.UITestingToolbox\Lombiq.Tests.UI\Services\UITestExecutor.cs:line 83

It seems that this only affects GitHub-hosted runners, and not GitRunners ones, see [this more recent successful build](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/7167417845).

This does NOT seem like a [Windows max path length](https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry) limitation, since the resulting _D:\a\Open-Source-Orchard-Core-Extensions\Open-Source-Orchard-Core-Extensions\test\Lombiq.UITestingToolbox\Lombiq.Tests.UI.Samples\Tests\BasicVisualVerificationTests_VerifyNavbar_By_ClassName[Contains]_-navbar-brand_Win32NT_chrome-headless-shell.png_ path is 248 characters long.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-755)

**Comment by wAsnk** [comment]
It looks like that file is indeed missing.

**Comment by Piedone** [comment]
Interesting. We introduced this exception in https://github.com/Lombiq/UI-Testing-Toolbox/issues/264 a while ago, so curious that it only started to fail now.

**Comment by Piedone** [comment]
PR builds pass, like [this one](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/7200593449). The same failed [after merge](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/7201121407). This may be an issue with GitHub's runners getting an image update that broke our test (https://github.com/actions/runner-images) but BuildJet not yet following it.

**Comment by Piedone** [comment]
Not BuildJet but GitRunners.

**Comment by Piedone** [comment]
Now the Ubuntu `dev` build fails: https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/7214786995
