### ISSUE TITLE
Security scan fails with an empty result list when used from a NuGet package. (OSOE-767)

### ISSUE THREAD

**Issue by sarahelsaig** [Lombiq/UI-Testing-Toolbox#336]
When imported from a project reference, the ZAP report doesn't fail the test on low risk level or suppressed alerts. The same doesn't seem to be true when used form the NuGet package.

For example check out [this](https://github.com/OrchardCMS/OrchardCore.Commerce/actions/runs/7462765354) run for https://github.com/OrchardCMS/OrchardCore.Commerce/pull/393/commits/b6d2897b68e2401ff8b1e87bfbb7c450d6c081f7. If you download the failure dump, the ZAP report shows no actual alerts so it shouldn't have been created:
![image](https://github.com/Lombiq/UI-Testing-Toolbox/assets/4007293/029f19c1-4563-4d35-939a-f4127b87956f)

On the other hand, if you look through the _2024-01-09-ZAP-Report-localhost.json_ in the same archive it has warnings for id 10202, which has been suppressed [here](https://github.com/OrchardCMS/OrchardCore.Commerce/blob/b6d2897b68e2401ff8b1e87bfbb7c450d6c081f7/test/OrchardCore.Commerce.Tests.UI/Tests/BasicTests/SecurityScanningTests.cs#L33). We know this suppression works, because that's the reason why the entries don't show up in the HTML report. For now the only workaround I found was to also provide [a custom assertion logic](https://github.com/OrchardCMS/OrchardCore.Commerce/blob/36c57f14bece48b2a85c884adb5af1d85da2d309/test/OrchardCore.Commerce.Tests.UI/Tests/BasicTests/SecurityScanningTests.cs#L37-L42) that detects and skips the alerts caused by the suppressed code.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-767)

**Comment by Piedone** [comment]
The [linked code's](https://github.com/OrchardCMS/OrchardCore.Commerce/blob/36c57f14bece48b2a85c884adb5af1d85da2d309/test/OrchardCore.Commerce.Tests.UI/Tests/BasicTests/SecurityScanningTests.cs#L37-L42) comment mentions there being a discrepancy between the HTML and JSON reports (the workflow artifacts are expired, unfortunately). So, this seems to be rather a ZAP bug to me than a difference between the source and NuGet versions of the project.

**Comment by Piedone** [comment]
Found this BTW: https://github.com/OrchardCMS/OrchardCore.Commerce/issues/404.

**Comment by Piedone** [comment]
It was an issue in our automation framework plans.
