### ISSUE TITLE
Don't include a file called .htmlvalidate.json by default (OSOE-844)

### ISSUE THREAD

**Issue by sarahelsaig** [Lombiq/UI-Testing-Toolbox#359]
Right now we [include](https://github.com/Lombiq/UI-Testing-Toolbox/blob/dev/Lombiq.Tests.UI/Lombiq.Tests.UI.csproj#L43-L46) _.htmlvalidate.json_  in the project csproj file. This means if you place your own _.htmlvalidate.json_ file in a project that references the NuGet package, it won't be enough. You also have to remove the import from the package first. This is not intuitive and as far as I can see it's not documented either. 

Instead, I suggest renaming it to something like _default.htmlvalidate.json_ and [including](https://github.com/Lombiq/UI-Testing-Toolbox/blob/dev/Lombiq.Tests.UI/Docs/Configuration.md#:~:text=Then%20you%20can%20change%20the%20configuration%20to%20use%20that:) a `HtmlValidationOptions` out of the box that uses _.htmlvalidate.json_ if the file exists and _default.htmlvalidate.json_ if it's missing.

---

Also I suggest including `"form-dup-name": "off"` in the default file, because we we have to turn that rule off for every project that uses boolean fields or just stock ASP.NET Core checkbox tag helpers because it expands into stuff like this:
```html
<input name="OrderPart.IsCorporation.Value" type="hidden" value="false"><input name="OrderPart.BillingAndShippingAddressesMatch.Value" type="hidden" value="false">
```

---

Also backport [this](https://github.com/OrchardCMS/OrchardCore.Commerce/pull/434/files/19f6c8e86a1ee23bf1a2f12556d2e74ff9f36aab#r1585216804) into UITT.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-844)

**Comment by Piedone** [comment]
Is the linked configuration a suitable workaround for you now? I.e., is this only about making configuration more convenient, or do we lack some functionality?

[`form-dup-name`](https://html-validate.org/rules/form-dup-name.html) fails on input fields with duplicate names. Why would that fail on the example code? The names there are unique.

**Comment by sarahelsaig** [comment]
> Is the linked configuration a suitable workaround for you now?

Actually no. [Now](https://github.com/OrchardCMS/OrchardCore.Commerce/actions/runs/8885732605?pr=434) the Linux run is broken that previously worked. 🫠

> form-dup-name fails on input fields with duplicate names. Why would that fail on the example code? The names there are unique.

Oof, I pasted without thinking. Anyway, here it is:
![image](https://github.com/Lombiq/UI-Testing-Toolbox/assets/4007293/bb95ca86-33ee-417c-ae91-f3ada0b3cd29)
And [here](https://github.com/OrchardCMS/OrchardCore.Commerce/blob/4c2a29ba837403c5a629f40fe0c604052423d625/src/Modules/OrchardCore.Commerce/Views/Checkout.cshtml#L86-L90) is the responsible code. (this is caused by `Microsoft.AspNetCore.Mvc.TagHelpers.InputTagHelper`)
I guess the purpose of the duplicate names to send the default `false` value if the actual checkbox is not checked. Normal HTML behavior is to not send anything in POST when the box is unchecked. I suppose the ASP.NET Core folks wanted to avoid the ambiguity between false and missing.

**Comment by Piedone** [comment]
Please work on this if it's blocking for you.

OK, indeed we can use `"form-dup-name": "off"` in the default config.

**Comment by Piedone** [comment]
Following up from https://github.com/OrchardCMS/OrchardCore.Commerce/pull/434, also include here the following:

- Document how to use `extends` in the json to extend the default file.
- Also add a per-test timeout configuration, see [here](https://github.com/OrchardCMS/OrchardCore.Commerce/pull/434#discussion_r1585216804).

**Comment by Piedone** [comment]
Hmm, we can actually set the timeout of async tests in xUnit directly: https://www.reddit.com/r/csharp/comments/zlulro/did_you_know_you_could_set_a_timeout_in_your/ So, I don't think we need a custom config, unless we can do a timeout that excludes waiting for the setup operation (that may be started by another test). However, that might work with the latest xUnit only, what I've updated to under https://github.com/Lombiq/UI-Testing-Toolbox/issues/355.

**Comment by sarahelsaig** [comment]
Unless I misunderstood this is opt-in, so you'd have to add the `Timeout` to every `Fact` individually. Having a required limit that you can configure globally or per-test is still worth it.

**Comment by Piedone** [comment]
Yeah.
