### ISSUE TITLE
Disable "allow pasting" warning in Chrome's dev tools (OSOE-873)

### ISSUE THREAD

**Issue by sarahelsaig** [Lombiq/UI-Testing-Toolbox#382]
[This noob-proofing security feature](https://developer.chrome.com/blog/self-xss) is incredibly annoying during test troubleshooting. We should see if it can be disabled, since it's not helpful to wed developers in the middle of a UI test.
![image](https://github.com/Lombiq/UI-Testing-Toolbox/assets/4007293/fd93e0dd-6a83-44fd-8234-d2549997e7b8)

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-873)

**Comment by Piedone** [comment]
It doesn't seem to be possible to disable this in any other way than indeed opening the console and typing `allow pasting`. How exactly is this causing an issue for you?

**Comment by sarahelsaig** [comment]
When I want to check a path from the code I'd start typing `$()` or `$x()` into the dev console, then try to paste like I'd do in my regular browser. The warning appears so I have to clear the input, type in "allow pasting" and then try again. **And the setting is not remembered across UI tests.** It's not a blocker, but it's very irritating and destroys the working experience.

It hard to believe that there is no automation flag to disable this in Chrome for Testing. I will research the question and open a Chrome issue if indeed it's not been raised (or more likely, link any already existing issue to keep an eye on).

**Comment by Piedone** [comment]
OK, thank you.

**Comment by sarahelsaig** [comment]
Looks like there is already something: https://issues.chromium.org/issues/41491762
I will try to implement it.

**Comment by Piedone** [comment]
Cool!
