### ISSUE TITLE
Support multi-tenancy (OSOE-364)

### ISSUE THREAD

**Issue by Piedone** [Lombiq/UI-Testing-Toolbox#80]
Currently, the Toolbox has some references to the Default site. If we want to test multi-tenancy, i.e. creating and launching tenants, then this needs to be extended.

- [x] Update `TenantTests` too. 
- [x] Needs prefixing in `GoToPageAsync()` and in `GoToRelativeUrlAsync()`.
- [x] Needs refactoring of `CreateAndEnterTenantAsync()`.
- [x] Support multi-tenancy with SQL Server. The logic changing the SQL Server connection string in the *appsettings.json* file can be substituted with using the [Database Shells Configuration Provider](https://docs.orchardcore.net/en/latest/docs/reference/core/Shells/#database-shells-configuration-provider and changing all connection strings in a query.
- [x] Support multi-tenancy with Azure Blob Storage. The logic in `AzureBlobStorageManager` can be changed to use a templated `{{ ShellSettings.Name }} BasePath`.
- [x] Support multi-tenancy for snapshots.
- [x] Refactor `Lombiq.Hosting.Tenants.FeaturesGuard.Tests.UI.Extensions.TestCaseUITestContextExtensions`.

**Comment by sarahelsaig** [comment]
The usage of "Default" could be replaced with [`UITestContext.TenantName`](https://github.com/Lombiq/UI-Testing-Toolbox/blob/caac57ddb82db01bfb785f84e70de52d626ee1b7/Lombiq.Tests.UI/Services/UITestContext.cs#L59) which is already used by the [`TypedRoute`](https://github.com/Lombiq/Helpful-Libraries/blob/e619b8b04755345156218fd57f5f226abf09dbc9/Lombiq.HelpfulLibraries/Libraries/Mvc/TypedRoute.cs). It's currently always set to "Default" and the user must manually change it, but it could be initialized using the way you described.
