### ISSUE TITLE
Create NuGet package for Helpful Libraries

### ISSUE THREAD

**Issue by hishamco** [Lombiq/UI-Testing-Toolbox#98]
Seems UI Testing uses Helpful Libraries which is created by Lombiq, it would be nice to publish them as NuGet or GitHub packages, so everyone can run this repo without need to clone the  Helpful Libraries repo

/cc @Piedone

**Comment by hishamco** [comment]
Once this done, I can modify the project references to make it work

**Comment by Piedone** [comment]
Yep, publishing our OSS projects on NuGet is something we have on our plate. Thanks for suggesting it!

**Comment by Piedone** [comment]
Work on this is tracked here: https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/issues/23

**Comment by Piedone** [comment]
We've published preview NuGet packages: https://www.nuget.org/packages?q=Lombiq.Tests.UI Could you check, please?
